version: '3.8'

services:
  mysql_db:
    image: mysql:8.0
    restart: always
    ports:
      - "7201:3306"
    volumes:
      - ./db/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: Newspaper
      MYSQL_ROOT_PASSWORD: password

  backend:
    build:
      dockerfile: Dockerfile
      context: "./backend"
    depends_on:
      - mysql_db
    volumes:
      - ./backend/data:/app/data
      - ./server:/app
    ports:
      - "8080:8080"
    environment:
      MYSQL_DATABASE: Newspaper
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: mysql_db

  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    ports:
      - "3000:3000"
    volumes:
      - /client/node_modules
      - ./client:/app

volumes:
  my-db:
