version: '3.8'

services:
  mysql_db:
    image: mysql:8.0
    restart: always
    container_name: newspaper_mysql
    cap_add:
      - SYS_NICE
    volumes:
      - "./setup.sql:/docker-entrypoint-initdb.d/setup.sql"
    ports:
      - "7201:3306"
    environment:
      # MYSQL_HOST_IP: localhost
      MYSQL_DATABASE: Newspaper
      # MYSQL_USER: MYSQL_USER
      # MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      # MYSQL_HOST: localhost

  backend:
    build:
      dockerfile: Dockerfile
      context: "./backend"
    depends_on:
      - mysql_db
    volumes:
      - /backend/node_modules
      - ./server:/app
    expose:
      - 8080
    environment:
      MYSQL_DATABASE: Newspaper
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: mysql_db

  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /client/node_modules
      - ./client:/app

volumes:
  my-db: