version: "3"

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - my_network

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql_db
    environment:
      DB_HOST: mysql_db
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
      DB_NAME: Newspaper
    networks:
      - my_network
    volumes:
      - ./backend/data:/app/data

  mysql_db:
    image: mysql:latest
    environment:
      DB_HOST: mysql_db
      MYSQL_DATABASE: Newspaper
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "7201:3306"
    networks:
      - my_network
    volumes:
      - ./mysql_db/data:/var/lib/mysql

networks:
  my_network:
