version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - frontend_backend

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      DATABASE_NAME: newspaper
      MYSQL_USERNAME: user
      MYSQL_PASSWORD: password
    networks:
      - frontend_backend
      - backend_mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_USER: user
      MYSQL_DATABASE: newspaper
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "7201:3306"
    networks:
      - backend_mysql
    volumes:
      - ./mysql/scripts:/docker-entrypoint-initdb.d
      - mysqldb:/var/lib/mysql

volumes:
  mysqldb:

networks:
  backend_mysql:
  frontend_backend:
