version: "3"
services:
  mysql:
    image: mysql
    restart: always
    ports:
      - 8080:8080
    environment:
      MYSQL_DATABASE: "books"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
      - mysql-data:/data/db
    networks:
      - backend

  client:
    build:
      dockerfile: Dockerfile
      context: "./client"
    networks:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - mysql-data:/data/db

  backend:
    build:
      dockerfile: Dockerfile
      context: "./backend"
    depends_on:
      - mysql
    volumes:
      - /backend/node_modules
      - ./server:/app
    networks:
      - backend
    # expose:
    #   - 8080
    environment:
      MYSQL_DATABASE: Newspaper
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: mysql_db

networks:
  backend:

volumes:
  mysql-data:
    #driver: local
